=== hmcts/cpp-context-stagingdlrm/stagingdlrm-command/stagingdlrm-command-api/src/raml/json/schema/stagingdlrm.receive-migrated-case-submission.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/stagingdlrm/command/api/receive-migrated-case-submission.json",
  "type": "object",
  "description": "Migrated Case File Submission",
  "properties": {
    "migratedCase": {
      "$ref": "http://cpp.moj.gov.uk/stagingdlrm/migrated/json/schemas/migrated-case.json"
    },
    "materials": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/stagingdlrm/migrated/json/schemas/migrated-material.json"
      }
    },
    "metadata": {
      "$ref": "http://cpp.moj.gov.uk/stagingdlrm/migrated/json/schemas/migrated-material-metadata.json"
    },
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "azureLocation": {
      "type": "string"
    }
  },
  "required": [
    "migratedCase",
    "metadata",
    "submissionId",
    "azureLocation"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-domain/stagingdlrm-domain-aggregate/src/test/resources/json/aggregate/xhibit/submission-without-materials.json
{
  "migratedCase": {
    "caseDetails": {
      "originatingOrganisation": "G94DV00",
      "initiationCode": "O",
      "prosecutorCaseReference": "TVL55117DFXXV",
      "dateReceived": "2024-01-15",
      "prosecutor": {
        "prosecutingAuthority": "GAEAA01"
      },
      "sendingCourt": "C50EX00",
      "receivingCourt": "B01LY00",
      "dateOfSending": "2024-08-23",
      "dateOfCommittal": "2024-01-15",
      "receiptType": "Either way case",
      "retrialIndicator": false
    },
    "hearings": [
      {
        "courtHearingLocation": "B01LY01",
        "dateOfHearing": "2024-11-10",
        "timeOfHearing": "10:05:01",
        "durationMinutes": 60,
        "courtRoomId": 60,
        "hearingType": "Trial",
        "listedDefendants": [
          {
            "prosecutorDefendantId": "def-ref-0001",
            "listedOffences": [
              "off-ref-0001"
            ]
          }
        ]
      }
    ],
    "defendants": [
      {
        "id": "aaaaaaaa-0000-0000-0000-000000000001",
        "prosecutorDefendantId": "def-ref-0001",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 1
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "off-ref-0001",
            "offenceCode": "CA03013",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      }
    ],
    "migrationSourceSystem": {
      "migrationSourceSystemName": "{{SOURCE_SYSTEM}}",
      "migrationSourceSystemCaseIdentifier": "case-identifier-0002"
    }
  },
  "metadata": {
    "id": "550e8400-e29b-41d4-a716-446655440004",
    "numberOfMaterials": 0
  },
  "submissionId": "22222222-3333-4444-5555-666666666666",
  "azureLocation": "{{SOURCE_SYSTEM}}/20082025/case-identifier-0002/22222222-3333-4444-5555-666666666666"
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-command/stagingdlrm-command-api/src/raml/json/stagingdlrm.receive-migrated-case-submission.json
{
  "migratedCase": {
    "caseDetails": {
      "originatingOrganisation": "B01NM00",
      "cpsOrganisation": "A30AB00",
      "otherPartyOfficerInCase": {
        "personalInformation": {
          "address": {
            "address1": "101",
            "address2": "56Police House",
            "address3": "Letsby Avenue",
            "address4": "Avon",
            "postcode": "HA1 2ER"
          },
          "contactDetails": {
            "primaryEmail": "vegaoic@test.dom",
            "work": "0117911911"
          },
          "firstName": "Gaylord",
          "lastName": "Blick",
          "title": "Baron"
        }
      },
      "caseId": "51cac7fb-387c-4d19-9c80-8963fa8cf222",
      "initiationCode": "J",
      "prosecutorCaseReference": "19YI1962686",
      "prosecutor": {
        "prosecutingAuthority": "G94DV00"
      }
    },
    "hearings": [
      {
        "courtHearingLocation": "C50EX02",
        "courtRoomId": 905,
        "dateOfHearing": "2024-11-26",
        "timeOfHearing": "12:10:01",
        "durationMinutes": 120,
        "hearingType": "FHG",
        "listedDefendants": [
          {
            "prosecutorDefendantId": "a9860e1a-8695-4fd4-8046-c1c4fe6c7f80",
            "listedOffences": [
              "427700bd-c116-4811-badb-bfa845d44d2f"
            ]
          },
          {
            "prosecutorDefendantId": "a9860e1a-8695-4fd4-8046-c1c4fe6c7f81",
            "listedOffences": [
              "357700bd-c116-4811-badb-bfa845d44d2f"
            ]
          }
        ]
      }
    ],
    "defendants": [
      {
        "prosecutorDefendantId": "a9860e1a-8695-4fd4-8046-c1c4fe6c7f80",
        "prosecutorDefendantReference": "DEFENDANT_REFERENCE1",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "numPreviousConvictions": 3,
        "individual": {
          "custodyStatus": "B",
          "personalInformation": {
            "title": "Mr",
            "forename": "John",
            "surname": "Jannie",
            "address": {
              "address1": "Oxford street",
              "address2": "Woodlane",
              "address3": "addressline 3",
              "address4": "Bristol",
              "address5": "Avon",
              "postcode": "M62 1NW"
            },
            "contactDetails": {
              "work": "020111222",
              "home": "020111223",
              "mobile": "07572222943",
              "primaryEmail": "scrooge.mcduck@mail.com",
              "secondaryEmail": "scrooge.mcduck2@mail.com"
            }
          },
          "selfDefinedInformation": {
            "ethnicity": "M3",
            "gender": "MALE",
            "dateOfBirth": "1998-06-08",
            "nationality": "SVK"
          }
        },
        "offences": [
          {
            "offenceCode": "TH68023",
            "offenceId": "427700bd-c116-4811-badb-bfa845d44d2f",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2024-09-24",
            "offenceCommittedEndDate": "2024-09-27",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "offenceWording",
            "chargeDate": "2024-09-27",
            "alcoholRelatedOffence": {
              "alcoholOrDrugLevelMethod": "A",
              "alcoholOrDrugLevelAmount": 100
            }
          }
        ],
        "pncIdentifier": "pncID3229",
        "croNumber": "croNO5596"
      }
    ],
    "migrationSourceSystem": {
      "migrationSourceSystemName": "XHIBIT",
      "migrationSourceSystemCaseIdentifier": "XHIBIT-2-HEARINGS"
    }
  },
  "materials": [
    {
      "id": "c1c48e76-aa4b-48e6-8255-fe8cbe8c1570",
      "fileType": "8",
      "documentType": 1,
      "azureLocation": "DL804361319/WitnessStatementDocument_1.pdf",
      "fileName": "WitnessStatementDocument_1.pdf"
    },
    {
      "id": "a0a67b32-da38-4f31-9a95-5da05b382a1f",
      "fileType": "8",
      "documentType": 1,
      "azureLocation": "DL804361319/WitnessStatementDocument_2.pdf",
      "fileName": "WitnessStatementDocument_2.pdf"
    }
  ],
  "metadata": {
    "id": "8e84fc15-d45c-42cf-8023-d0b98856209a",
    "numberOfMaterials": 2
  },
  "submissionId": "550e8400-e29b-41d4-a716-446655440000",
  "azureLocation": "28DI10239082"
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-integration-test/src/test/resources/xhibit/stagingdlrm.receive-migrated-case-submission-from-xhibit-with-casemarker.json
{
  "migratedCase": {
    "caseDetails": {
      "originatingOrganisation": "G94DV00",
      "initiationCode": "O",
      "dateReceived": "2024-01-15",
      "sendingCourt": "C01BL00",
      "receivingCourt": "C01BL00",
      "dateOfSending": "2024-08-23",
      "dateOfCommittal": "2024-01-15",
      "receiptType": "Either way case",
      "retrialIndicator": false,
      "prosecutorCaseReference": "TVL55117DFXXV",
      "caseMarkers": [
        {
          "markerTypeCode": "CD"
        }
      ],
      "prosecutor": {
        "prosecutingAuthority": "GAEAA01"
      }
    },
    "hearings": [
      {
        "courtHearingLocation": "C01LY01",
        "dateOfHearing": "2024-11-10",
        "timeOfHearing": "11:10:01",
        "durationMinutes": 60,
        "courtRoomId": 60,
        "hearingType": "",
        "listedDefendants": [
          {
            "prosecutorDefendantId": "XHIBIT-defendant-id-1",
            "listedOffences": [
              "XHIBIT-offence-id-1"
            ]
          },
          {
            "prosecutorDefendantId": "XHIBIT-defendant-id-2",
            "listedOffences": [
              "XHIBIT-offence-id-2"
            ]
          }
        ]
      }
    ],
    "defendants": [
      {
        "prosecutorDefendantId": "XHBIT-defendant-id-1",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "custodyStatus": "C",
          "custodyTimeLimit": "2018-09-10",
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 2
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "XHIBIT-offence-id-1",
            "offenceCode": "CA03013",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      },
      {
        "prosecutorDefendantId":"XHIBIT-defendant-id-2",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 1
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "XHIBIT-offence-id-2",
            "offenceCode": "DA03014",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      }
    ],
    "migrationSourceSystem" :{
      "migrationSourceSystemName" : "XHIBIT",
      "migrationSourceSystemCaseIdentifier" : "This is from XHIBIT"
    }
  },
  "materials": [
    {
      "id": "550e8400-e29b-41d4-a716-446655440001",
      "azureLocation": "http://inazure/secrets/1",
      "fileName": "Audio Recording one",
      "fileType": ".wav",
      "documentType": 3
    },
    {
      "id": "550e8400-e29b-41d4-a716-446655440000",
      "azureLocation": "http://inazure/secrets/2",
      "fileName": "Audio Recording two",
      "fileType": ".wav",
      "documentType": 3
    }
  ],
  "metadata": {
    "id": "550e8400-e29b-41d4-a716-446655440003",
    "numberOfMaterials": 2
  },
  "submissionId": "SUBMISSION_ID",
  "azureLocation": "TVL55117DFXXV"
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-integration-test/src/test/resources/stagingdlrm.receive-migrated-case-submission-missing-address.json
{
  "migratedCase": {
    "caseDetails": {
      "originatingOrganisation": "G94DV00",
      "initiationCode": "O",
      "prosecutorCaseReference": "TVL55117DFXXV",
      "dateReceived": "2024-01-15",
      "prosecutor": {
        "prosecutingAuthority": "GAEAA01"
      },
      "sendingCourt": "C50EX00",
      "receivingCourt": "B01LY00",
      "dateOfSending": "2024-08-23",
      "dateOfCommittal": "2024-01-15",
      "receiptType": "Either way case",
      "retrialIndicator": false
    },
    "hearings": [
      {
        "courtHearingLocation": "B01LY01",
        "dateOfHearing": "2024-11-10",
        "timeOfHearing": "10:05:01",
        "durationMinutes": 60,
        "courtRoomId": 60,
        "hearingType": "Trial",
        "listedDefendants": [
          {
            "prosecutorDefendantId": "LIBRA-defendant-id-1",
            "listedOffences": [
              "LIBRA-offence-id-1"
            ]
          },
          {
            "prosecutorDefendantId": "LIBRA-defendant-id-2",
            "listedOffences": [
              "LIBRA-offence-id-2"
            ]
          }
        ]
      }
    ],
    "defendants": [
      {
        "prosecutorDefendantId": "LIBRA-defendant-id-1",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 1
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "LIBRA-offence-id-1",
            "offenceCode": "CA03013",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      },
      {
        "prosecutorDefendantId": "LIBRA-defendant-id-2",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 2
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "LIBRA-offence-id-2",
            "offenceCode": "DA03014",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      }
    ],
    "migrationSourceSystem": {
      "migrationSourceSystemName": "LIBRA",
      "migrationSourceSystemCaseIdentifier": "This is from Libra"
    }
  },
  "materials": [
    {
      "id": "550e8400-e29b-41d4-a716-446655440001",
      "azureLocation": "http://inazure/secrets/1",
      "fileName": "Audio Recording one",
      "fileType": ".wav",
      "documentType": 3
    },
    {
      "id": "550e8400-e29b-41d4-a716-446655440000",
      "azureLocation": "http://inazure/secrets/2",
      "fileName": "Audio Recording two",
      "fileType": ".wav",
      "documentType": 3
    }
  ],
  "metadata": {
    "id": "550e8400-e29b-41d4-a716-446655440003",
    "numberOfMaterials": 2
  },
  "submissionId": "SUBMISSION_ID",
  "azureLocation": "TVL55117DFXXV"
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-integration-test/src/test/resources/stagingdlrm.receive-migrated-case-submission-no-defendants.json
{
  "migratedCase": {
    "caseDetails": {
      "originatingOrganisation": "G94DV00",
      "initiationCode": "O",
      "dateReceived": "2024-01-15",
      "sendingCourt": "C01BL00",
      "receivingCourt": "C01BL00",
      "dateOfSending": "2024-08-23",
      "dateOfCommittal": "2024-01-15",
      "receiptType": "Either way case",
      "retrialIndicator": false,
      "prosecutorCaseReference": "TVL55117DFXXV",
      "prosecutor": {
        "prosecutingAuthority": "GAEAA01"
      }
    },
    "hearings": [
      {
        "courtHearingLocation": "C01LY01",
        "dateOfHearing": "2024-11-10",
        "timeOfHearing": "11:10:01",
        "durationMinutes": 60,
        "courtRoomId": 60,
        "hearingType": "",
        "listedDefendants": [
          {
            "prosecutorDefendantId": "XHIBIT-defendant-id-1",
            "listedOffences": [
              "XHIBIT-offence-id-1"
            ]
          }
        ]
      }
    ],
    "defendants": [],
    "migrationSourceSystem": {
      "migrationSourceSystemName": "XHIBIT",
      "migrationSourceSystemCaseIdentifier": "This is from XHIBIT"
    }
  },
  "materials": [
    {
      "id": "550e8400-e29b-41d4-a716-446655440001",
      "azureLocation": "http://inazure/secrets/1",
      "fileName": "Audio Recording one",
      "fileType": ".wav",
      "documentType": 3
    }
  ],
  "metadata": {
    "id": "550e8400-e29b-41d4-a716-446655440003",
    "numberOfMaterials": 1
  },
  "submissionId": "SUBMISSION_ID",
  "azureLocation": "TVL55117DFXXV"
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-integration-test/src/test/resources/xhibit/stagingdlrm.receive-migrated-case-submission.json
{
  "migratedCase": {
    "caseDetails": {
      "originatingOrganisation": "G94DV00",
      "initiationCode": "O",
      "prosecutorCaseReference": "TVL55117DFXXV",
      "dateReceived": "2024-01-15",
      "prosecutor": {
        "prosecutingAuthority": "GAEAA01"
      },
      "sendingCourt": "C50EX00",
      "receivingCourt": "B01LY00",
      "dateOfSending": "2024-08-23",
      "dateOfCommittal": "2024-01-15",
      "receiptType": "Either way case",
      "retrialIndicator": false
    },
    "hearings": [
      {
        "courtHearingLocation": "B01LY01",
        "dateOfHearing": "2024-11-10",
        "timeOfHearing": "10:05:01",
        "durationMinutes": 60,
        "courtRoomId": 60,
        "hearingType": "Trial",
        "listedDefendants": [
          {
            "prosecutorDefendantId": "XHIBIT-defendant-id-1",
            "listedOffences": [
              "XHIBIT-offence-id-1"
            ]
          },
          {
            "prosecutorDefendantId": "XHIBIT-defendant-id-2",
            "listedOffences": [
              "XHIBIT-offence-id-2"
            ]
          }
        ]
      }
    ],
    "defendants": [
      {
        "prosecutorDefendantId": "XHIBIT-defendant-id-1",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 1
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "XHIBIT-offence-id-1",
            "offenceCode": "CA03013",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      },
      {
        "prosecutorDefendantId": "XHIBIT-defendant-id-2",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 2
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "XHIBIT-offence-id-2",
            "offenceCode": "DA03014",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      }
    ],
    "migrationSourceSystem": {
      "migrationSourceSystemName": "XHIBIT",
      "migrationSourceSystemCaseIdentifier": "xhibit-case-identifier-0001"
    }
  },
  "materials": [
    {
      "id": "550e8400-e29b-41d4-a716-446655440001",
      "azureLocation": "http://inazure/secrets/1",
      "fileName": "Audio Recording one",
      "fileType": ".pdf",
      "documentType": 3
    },
    {
      "id": "550e8400-e29b-41d4-a716-446655440000",
      "azureLocation": "http://inazure/secrets/2",
      "fileName": "Audio Recording two",
      "fileType": ".pdf",
      "documentType": 3
    }
  ],
  "metadata": {
    "id": "550e8400-e29b-41d4-a716-446655440003",
    "numberOfMaterials": 2
  },
  "submissionId": "SUBMISSION_ID",
  "azureLocation": "TVL55117DFXXV"
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-azure-functions/src/test/resources/json/command-helper/expected-without-materials.json
{
  "migratedCase": {
    "caseDetails": {
      "prosecutorCaseReference": "TVL55117DFXXV",
      "initiationCode": "H"
    },
    "hearings": [
      { "hearingType": "FHG" }
    ],
    "defendants": [
      { "offences": [ { "offenceCode": "CA03013" } ] }
    ],
    "migrationSourceSystem": {
      "migrationSourceSystemName": "{{SOURCE_SYSTEM}}",
      "migrationSourceSystemCaseIdentifier": "{{SOURCE_SYSTEM}}-1234567890"
    }
  },
  "metadata": {
    "id": "GENERATED-AT-RUNTIME",
    "numberOfMaterials": 0
  },
  "submissionId": "11111111-2222-3333-4444-555555555555",
  "azureLocation": "batch-0001"
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-integration-test/src/test/resources/stagingdlrm.receive-migrated-case-submission-with-multiple-hearing.json
{
  "migratedCase": {
    "caseDetails": {
      "originatingOrganisation": "G94DV00",
      "initiationCode": "O",
      "dateReceived": "2024-01-15",
      "sendingCourt": "C01BL00",
      "receivingCourt": "C01BL00",
      "dateOfSending": "2024-08-23",
      "dateOfCommittal": "2024-01-15",
      "receiptType": "Commital for sentence",
      "retrialIndicator": false,
      "prosecutorCaseReference": "TVL55117DFXXV",
      "prosecutor": {
        "prosecutingAuthority": "GAEAA01"
      }
    },
    "hearings": [
      {
        "courtHearingLocation": "B01LY01",
        "dateOfHearing": "2024-11-10",
        "timeOfHearing": "10:05:01",
        "durationMinutes": 60,
        "courtRoomId": 60,
        "hearingType": "",
        "listedDefendants": [
          {
            "prosecutorDefendantId": "LIBRA-defendant-id-1",
            "listedOffences": [
              "LIBRA-offence-id-1"
            ]
          },
          {
            "prosecutorDefendantId": "LIBRA-defendant-id-2",
            "listedOffences": [
              "LIBRA-offence-id-2"
            ]
          }
        ]
      },
      {
        "courtHearingLocation": "B01LY02",
        "durationMinutes": 90,
        "weekCommencingDate": {
          "startDate": "2025-05-10",
          "duration": 5
        },
        "hearingType": "",
        "listedDefendants": [
          {
            "prosecutorDefendantId": "LIBRA-defendant-id-1",
            "listedOffences": [
              "LIBRA-offence-id-1"
            ]
          },
          {
            "prosecutorDefendantId": "LIBRA-defendant-id-2",
            "listedOffences": [
              "LIBRA-offence-id-2"
            ]
          }
        ]
      }
    ],
    "defendants": [
      {
        "prosecutorDefendantId": "LIBRA-defendant-id-1",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 1
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "LIBRA-offence-id-1",
            "offenceCode": "CA03013",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      },
      {
        "prosecutorDefendantId":"LIBRA-defendant-id-2",
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "forename": "John",
            "surname": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "W1",
            "gender": 1
          }
        },
        "offences": [
          {
            "prosecutorOffenceId": "LIBRA-offence-id-2",
            "offenceCode": "DA03014",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04"
          }
        ]
      }
    ],
    "migrationSourceSystem": {
      "migrationSourceSystemName": "LIBRA",
      "migrationSourceSystemCaseIdentifier": "This is from Libra"
    }
  },
  "materials": [
    {
      "id": "550e8400-e29b-41d4-a716-446655440001",
      "azureLocation": "http://inazure/secrets/1",
      "fileName": "Audio Recording one",
      "fileType": ".wav",
      "documentType": 3
    },
    {
      "id": "550e8400-e29b-41d4-a716-446655440000",
      "azureLocation": "http://inazure/secrets/2",
      "fileName": "Audio Recording two",
      "fileType": ".wav",
      "documentType": 3
    }
  ],
  "metadata": {
    "id": "550e8400-e29b-41d4-a716-446655440003",
    "numberOfMaterials": 2
  },
  "submissionId": "SUBMISSION_ID",
  "azureLocation": "TVL55117DFXXV"
}
