=== hmcts/cpp-context-stagingdlrm/stagingdlrm-domain/stagingdlrm-domain-value-schema/src/main/resources/json/schema/individual.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/stagingdlrm/json/schemas/individual.json",
  "type": "object",
  "description": "Individual Details",
  "properties": {
    "selfDefinedInformation": {
      "$ref": "http://cpp.moj.gov.uk/stagingdlrm/json/schemas/self-defined-information.json"
    },
    "personalInformation": {
      "$ref": "http://cpp.moj.gov.uk/stagingdlrm/json/schemas/personal-information.json"
    },
    "parentGuardianInformation": {
      "$ref": "http://cpp.moj.gov.uk/stagingdlrm/json/schemas/parent-guardian-information.json"
    },
    "custodyStatus": {
      "type": "string",
      "maxLength": 1
    },
    "custodyTimeLimit": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date",
      "description": "date of custody time limit"
    },
    "bailConditions": {
      "type": "string",
      "maxLength": 2500
    },
    "driverNumber": {
      "type": "string",
      "maxLength": 16,
      "description": "A driver's licence number."
    },
    "nationalInsuranceNumber": {
      "$ref": "http://cpp.moj.gov.uk/stagingdlrm/json/schemas/pcf-definitions.json#/definitions/nationalInsuranceNumber"
    },
    "licenseCode": {
      "type": "string",
      "maxLength": 1,
      "description": "Identifies the type of driving licence. Previously known as Licence Type."
    }
  },
  "required": [
    "personalInformation",
    "selfDefinedInformation"
  ]
}

=== hmcts/cpp-context-stagingdlrm/stagingdlrm-domain/stagingdlrm-domain-value-schema/src/main/resources/json/examples/individual-example.json
{
  "driverNumber" : "AS",
  "nationalInsuranceNumber" : "QQ 12 34 56 C",
  "personalInformation": {
    "title": "Baron",
    "firstName": "John",
    "lastName": "Smith",
    "occupation": "Software Developer",
    "occupationCode": 43,
    "address": {
      "address1": "66 Exeter Street",
      "address2": "line 2",
      "address3": "line 3",
      "address4": "line 4",
      "address5": "line 5",
      "postcode": "M60 1NW"
    },
    "contactDetails": {
      "work" : "020111222",
      "home" : "020111223",
      "mobile" : "07572222943",
      "primaryEmail" : "scrooge.mcduck@mail.com",
      "secondaryEmail" : "scrooge.mcduck2@mail.com"
    }
  },
  "selfDefinedInformation": {
    "ethnicity": "white",
    "gender": "MALE",
    "dateOfBirth": "1989-04-18",
    "nationality": "SVK"
  }
}
